import { z } from 'zod/v4';

// ============================================================================
// FLASHCARD SCHEMAS
// ============================================================================

// --- Flashcard Input (extracted from user query) ---
export const flashcardInputSchema = z.object({
  topic: z.string().min(2).max(200),
  cardCount: z.number().int().min(1).max(30),
  difficulty: z.enum(['easy', 'medium', 'hard']),
  focusAreas: z.array(z.string().max(100)).max(5).optional(),
});

// --- Flashcard Output (generated by LLM) ---
export const flashcardItemSchema = z.object({
  front: z.string().min(5).max(300).describe('The question, term, or concept'),
  back: z.string().min(10).max(500).describe('The answer, definition, or explanation'),
});

export const flashcardOutputSchema = z.object({
  title: z.string().min(5).max(200),
  topicSummary: z.string().min(10).max(500).describe('A brief 2-3 sentence overview of the topic'),
  cards: z.array(flashcardItemSchema).max(30),
});

// --- Validation Result (internal) ---
export const flashcardValidationResultSchema = z.object({
  valid: z.boolean(),
  errors: z.array(z.string()),
  warnings: z.array(z.string()),
});

// ============================================================================
// TYPES
// ============================================================================

export type FlashcardInput = z.infer<typeof flashcardInputSchema>;
export type FlashcardItem = z.infer<typeof flashcardItemSchema>;
export type FlashcardOutput = z.infer<typeof flashcardOutputSchema>;
export type FlashcardValidationResult = z.infer<typeof flashcardValidationResultSchema>;
