import { z } from 'zod/v4';

// ============================================================================
// QUIZ SCHEMAS
// ============================================================================

// --- Quiz Input (extracted from user query) ---
export const quizInputSchema = z.object({
  topic: z.string().min(2).max(200),
  questionCount: z.number().int().min(1).max(20),
  questionTypes: z.array(z.enum(['multiple_choice', 'true_false'])).min(1),
  difficulty: z.enum(['easy', 'medium', 'hard']),
  focusAreas: z.array(z.string().max(100)).max(5).optional(),
});

// --- Quiz Output (generated by LLM) ---
export const quizQuestionSchema = z.object({
  type: z.enum(['multiple_choice', 'true_false']),
  question: z.string().min(10).max(500),
  options: z.array(z.string().min(1).max(300)).min(2).max(6),
  correctAnswer: z.string().min(1).max(300),
  explanation: z.string().min(10).max(500),
});

export const quizOutputSchema = z.object({
  title: z.string().min(5).max(200),
  topicSummary: z.string().min(10).max(500).describe('A brief 2-3 sentence overview of the topic to introduce the quiz'),
  questions: z.array(quizQuestionSchema).max(20),
});

// --- Success/Failure Observations ---
export const quizGenerationSuccessSchema = z.object({
  success: z.literal(true),
  quiz: quizOutputSchema,
  input: quizInputSchema,
  questionsGenerated: z.number().int(),
  questionsRequested: z.number().int(),
});

export const quizGenerationFailureSchema = z.object({
  success: z.literal(false),
  input: quizInputSchema.optional(),
  error_type: z.enum([
    'intent_extraction_failed',
    'insufficient_context',
    'generation_failed',
    'validation_failed',
  ]),
  error_message: z.string().min(10).max(500),
  validationErrors: z.array(z.string()).optional(),
});

// --- Validation Result (internal) ---
export const quizValidationResultSchema = z.object({
  valid: z.boolean(),
  errors: z.array(z.string()),
  warnings: z.array(z.string()),
});

// ============================================================================
// TYPES
// ============================================================================

export type QuizInput = z.infer<typeof quizInputSchema>;
export type QuizQuestion = z.infer<typeof quizQuestionSchema>;
export type QuizOutput = z.infer<typeof quizOutputSchema>;
export type QuizGenerationSuccess = z.infer<typeof quizGenerationSuccessSchema>;
export type QuizGenerationFailure = z.infer<typeof quizGenerationFailureSchema>;
export type QuizValidationResult = z.infer<typeof quizValidationResultSchema>;
